/**
 * ClaimButton
 *
 * Allows the user to claim their USDC from the Polygon HTLC using their secret.
 * The claim is processed server-side via Gelato Relay for gasless transactions.
 */

import { useState } from "react";
import { Button } from "#/components/ui/button";
import { api } from "../api";

interface ClaimButtonProps {
  swapId: string; // The swap ID
  secret: string; // The secret generated by the client (32-byte hex string)
  onClaimSuccess: () => void;
  onClaimError: (error: string) => void;
}

export function ClaimButton({
  swapId,
  secret,
  onClaimSuccess,
  onClaimError,
}: ClaimButtonProps) {
  const [isClaiming, setIsClaiming] = useState(false);

  const handleClaim = async () => {
    setIsClaiming(true);

    try {
      // Remove 0x prefix if present
      const cleanSecret = secret.startsWith("0x") ? secret.slice(2) : secret;

      console.log("Claiming with parameters:", {
        swapId,
        secret: cleanSecret,
      });

      await api.claimGelato(swapId, cleanSecret);

      console.log("Claim request sent successfully");
      onClaimSuccess();
    } catch (error) {
      console.error("Failed to claim:", error);
      onClaimError(
        error instanceof Error ? error.message : "Failed to claim USDC",
      );
    } finally {
      setIsClaiming(false);
    }
  };

  return (
    <div className="space-y-2">
      <Button
        onClick={handleClaim}
        disabled={isClaiming || !secret || !swapId}
        className="w-full"
      >
        {isClaiming ? "Claiming..." : "Claim USDC (100% Gasless)"}
      </Button>
      <p className="text-muted-foreground text-center text-xs">
        Gas fees fully sponsored via Gelato Relay - no fees for you!
      </p>
    </div>
  );
}
